In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('players_20.csv')

In [8]:
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [9]:
df.set_index('short_name', inplace=True)

In [10]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [11]:
df[["long_name"	,"age"	,"dob"	,"height_cm"	,"weight_kg"	,"nationality"	,"club"]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [12]:
df.loc['L. Messi']

sofifa_id                                                158023
player_url    https://sofifa.com/player/158023/lionel-messi/...
long_name                        Lionel Andrés Messi Cuccittini
age                                                          32
dob                                                  1987-06-24
                                    ...
lb                                                         63+2
lcb                                                        52+2
cb                                                         52+2
rcb                                                        52+2
rb                                                         63+2
Name: L. Messi, Length: 103, dtype: object

In [15]:
str(df.loc['L. Messi','weight_kg'])

'72'

In [14]:
df.loc['L. Messi','nationality']

'Argentina'

In [16]:
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [18]:
df.loc['L. Messi',:]

sofifa_id                                                158023
player_url    https://sofifa.com/player/158023/lionel-messi/...
long_name                        Lionel Andrés Messi Cuccittini
age                                                          32
dob                                                  1987-06-24
                                    ...
lb                                                         63+2
lcb                                                        52+2
cb                                                         52+2
rcb                                                        52+2
rb                                                         63+2
Name: L. Messi, Length: 103, dtype: object

In [19]:
# lets do it with list

In [20]:
df.loc[['L. Messi','Cristiano Ronaldo']]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3

In [21]:
df.loc[['L. Messi','Cristiano Ronaldo'], 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [22]:
df.loc[['L. Messi','Cristiano Ronaldo'], :]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3

In [24]:
df.loc[['L. Messi','Cristiano Ronaldo'], ['height_cm','weight_kg','age']]

                   height_cm  weight_kg  age
short_name
L. Messi                 170         72   32
Cristiano Ronaldo        187         83   34

In [25]:
df.loc[['L. Messi','Cristiano Ronaldo'], 'long_name':'club']

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [27]:
df.index[:10]

Index(['L. Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'J. Oblak', 'E. Hazard',
       'K. De Bruyne', 'M. ter Stegen', 'V. van Dijk', 'L. Modrić',
       'M. Salah'],
      dtype='object', name='short_name')

In [30]:
df.loc[df['height_cm']<180,'long_name':'club']

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool
...,...,...,...,...,...,...,...
Wang Peng,王鹏,21,1997-11-16,175,70,China PR,Guangzhou R&F FC
J. Ryan,Jack Ryan,19,2000-02-07,178,75,Republic of Ireland,UCD AFC
M. Gallagher,Michael Gallagher,18,2000-07-09,178,70,Republic of Ireland,Finn Harps
M. Sagaf,Mohammed Sagaf,21,1997-11-12,177,70,England,Carlisle United
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC

In [31]:
top10 = df.loc['L. Messi':'M. Salah', 'long_name':'club']

In [33]:
top10

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool

In [35]:
top10.loc[top10['height_cm']<180, 'long_name':'club']

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool

In [39]:
df[(df['nationality'] == 'Brazil') & (df['club'] == 'Real Madrid')]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
Casemiro,200145,https://sofifa.com/player/200145/carlos-henriq...,Carlos Henrique Venancio Casimiro,27,1992-02-23,185,84,Brazil,Real Madrid,87,...,78+3,84+3,84+3,84+3,78+3,79+3,84+3,84+3,84+3,79+3
Marcelo,176676,https://sofifa.com/player/176676/marcelo-vieir...,Marcelo Vieira da Silva Júnior,31,1988-05-12,174,75,Brazil,Real Madrid,85,...,82+3,81+3,81+3,81+3,82+3,81+3,79+3,79+3,79+3,81+3
Éder Militão,240130,https://sofifa.com/player/240130/eder-gabriel-...,Éder Gabriel Militão,21,1998-01-18,186,78,Brazil,Real Madrid,81,...,78+2,76+2,76+2,76+2,78+2,78+2,79+2,79+2,79+2,78+2
Vinícius Jr.,238794,https://sofifa.com/player/238794/vinicius-jose...,Vinícius José de Oliveira Júnior,18,2000-07-12,176,73,Brazil,Real Madrid,79,...,58+2,53+2,53+2,53+2,58+2,53+2,43+2,43+2,43+2,53+2
Rodrygo,243812,https://sofifa.com/player/243812/rodrygo-silva...,Rodrygo Silva de Goes,18,2001-01-09,174,64,Brazil,Real Madrid,76,...,56+2,48+2,48+2,48+2,56+2,52+2,41+2,41+2,41+2,52+2
Lucas Silva,209749,https://sofifa.com/player/209749/lucas-silva-b...,Lucas Silva Borges,26,1993-02-16,182,80,Brazil,Real Madrid,74,...,70+2,72+2,72+2,72+2,70+2,69+2,71+2,71+2,71+2,69+2

# testing iloc

In [44]:
df.head()

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [48]:
top10.iloc[0,3]

np.int64(170)

In [53]:
df.iloc[1,6]

np.int64(83)

In [54]:
df.iloc[0:11,3:5]

                   age         dob
short_name
L. Messi            32  1987-06-24
Cristiano Ronaldo   34  1985-02-05
Neymar Jr           27  1992-02-05
J. Oblak            26  1993-01-07
E. Hazard           28  1991-01-07
K. De Bruyne        28  1991-06-28
M. ter Stegen       27  1992-04-30
V. van Dijk         27  1991-07-08
L. Modrić           33  1985-09-09
M. Salah            27  1992-06-15
K. Mbappé           20  1998-12-20

In [51]:
df.iloc[0,:]

sofifa_id                                                158023
player_url    https://sofifa.com/player/158023/lionel-messi/...
long_name                        Lionel Andrés Messi Cuccittini
age                                                          32
dob                                                  1987-06-24
                                    ...
lb                                                         63+2
lcb                                                        52+2
cb                                                         52+2
rcb                                                        52+2
rb                                                         63+2
Name: L. Messi, Length: 103, dtype: object